server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    root: INFO

spring:
  application:
    name: sufi-availability-service

management:
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        availability_request_duration_seconds: true
      percentiles:
        availability_request_duration_seconds: 0.5, 0.95, 0.99
      sla:
        availability_request_duration_seconds: 100ms, 500ms, 1s, 3s
    web:
      server:
        request:
          autotime:
            enabled: true